import{a as d,S as m,i as f}from"./assets/vendor-C4-ZuMk8.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const y="46773750-2567d69edc75d4703fc28c418",h="https://pixabay.com/api/";async function g(r){const s=new URLSearchParams({key:y,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:30});return d.get(`${h}?${s}`).then(o=>o.data).catch(o=>{console.log(o.message)})}const c=document.querySelector(".list"),L=new m(".list .list-item a",{captionsData:"alt",captionDelay:250});function b(r){const s=r.map(({largeImageURL:o,webformatURL:n,tags:e,likes:t,views:i,comments:p,downloads:u})=>`<li class="list-item"><a href="${o}">
            <div class="image-box">
              <img src="${n}" alt="${e}" width="360"></div>
              <ul class="description">
                <li><p>Likes:</p><span>${t}</span></li>
                <li><p>Views:</p><span>${i}</span></li>
                <li><p>Comments:</p><span>${p}</span></li>
                <li><p>Downloads:</p><span>${u}</span></li>
              </ul>
              
            </a></li>`).join("");c.insertAdjacentHTML("beforeend",s),L.refresh()}function S(){c.innerHTML=""}const $=document.querySelector(".list"),q=document.querySelector(".searching-form"),a=document.querySelector(".loader");q.addEventListener("submit",w);async function w(r){r.preventDefault(),$.innerHTML="",a.style.display="block";const s=r.target.elements.search.value.trim();if(!s){a.style.display="none",l("error");return}const o=await g(s);a.style.display="none",parseInt(o.totalHits)?b(o.hits):(S(),l("sorry"))}function l(r){f.error({title:r==="error"?"Error":"",message:r==="error"?"Request cannot be empty, please, enter text":"Sorry, there are no images matching your search query. Please try again!",position:"topRight",maxWidth:"400px",color:"#EF4040",theme:"dark"})}
//# sourceMappingURL=index.js.map
